"""initial schema

Revision ID: 6d878bf70def
Revises: 
Create Date: 2026-04-21 02:17:37.530889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d878bf70def'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborations',
    sa.Column('collaboration_id', sa.String(length=36), nullable=False),
    sa.Column('researcher_ids', sa.Text(), nullable=True),
    sa.Column('partner_institution', sa.String(length=255), nullable=True),
    sa.Column('partner_country', sa.String(length=100), nullable=True),
    sa.Column('collaboration_type', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('nature_of_work', sa.String(length=255), nullable=True),
    sa.Column('funding_amount_inr_crores', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('research_area', sa.String(length=100), nullable=True),
    sa.Column('access_tier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('collaboration_id')
    )
    op.create_index('idx_collaborations_partner', 'collaborations', ['partner_institution'], unique=False)
    op.create_index('idx_collaborations_status', 'collaborations', ['status'], unique=False)
    op.create_index('idx_collaborations_tier', 'collaborations', ['access_tier'], unique=False)
    op.create_index('idx_collaborations_type', 'collaborations', ['collaboration_type'], unique=False)
    op.create_table('patents',
    sa.Column('patent_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('inventor_ids', sa.Text(), nullable=True),
    sa.Column('applicant_institution', sa.String(length=255), nullable=True),
    sa.Column('patent_office', sa.String(length=100), nullable=True),
    sa.Column('application_number', sa.String(length=100), nullable=True),
    sa.Column('filing_date', sa.String(length=50), nullable=True),
    sa.Column('grant_date', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('research_area', sa.String(length=100), nullable=True),
    sa.Column('patent_type', sa.String(length=100), nullable=True),
    sa.Column('claims_count', sa.Integer(), nullable=True),
    sa.Column('access_tier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('patent_id')
    )
    op.create_index('idx_patents_research_area', 'patents', ['research_area'], unique=False)
    op.create_index('idx_patents_status', 'patents', ['status'], unique=False)
    op.create_index('idx_patents_tier', 'patents', ['access_tier'], unique=False)
    op.create_table('research_documents',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('researcher_ids', sa.Text(), nullable=True),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('research_area_tags', sa.Text(), nullable=True),
    sa.Column('access_tier', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index('idx_research_docs_category', 'research_documents', ['category'], unique=False)
    op.create_index('idx_research_docs_tier', 'research_documents', ['access_tier'], unique=False)
    op.create_index('idx_research_docs_year', 'research_documents', ['publication_year'], unique=False)
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('principal_investigator_id', sa.String(length=36), nullable=False),
    sa.Column('co_pis', sa.Text(), nullable=True),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('funding_agency', sa.String(length=255), nullable=True),
    sa.Column('sanctioned_amount_inr_crores', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('research_area', sa.String(length=100), nullable=True),
    sa.Column('access_tier', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['principal_investigator_id'], ['researchers.researcher_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('idx_projects_agency', 'projects', ['funding_agency'], unique=False)
    op.create_index('idx_projects_pi', 'projects', ['principal_investigator_id'], unique=False)
    op.create_index('idx_projects_research_area', 'projects', ['research_area'], unique=False)
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.create_index('idx_projects_tier', 'projects', ['access_tier'], unique=False)
    op.drop_table('schema_migrations')
    op.add_column('funding_records', sa.Column('project_id', sa.String(length=36), nullable=True))
    op.add_column('funding_records', sa.Column('fiscal_year', sa.String(length=20), nullable=True))
    op.alter_column('funding_records', 'funding_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('funding_records', 'researcher_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
    op.alter_column('funding_records', 'institution_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
    op.alter_column('funding_records', 'agency',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('funding_records', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('funding_records', 'start_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('funding_records', 'end_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('funding_records', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('funding_records', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('funding_records', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_funding_amount'), table_name='funding_records')
    op.create_index('idx_funding_fiscal_year', 'funding_records', ['fiscal_year'], unique=False)
    op.create_index('idx_funding_project', 'funding_records', ['project_id'], unique=False)
    op.create_index('idx_funding_tier', 'funding_records', ['access_tier'], unique=False)
    op.create_foreign_key(None, 'funding_records', 'projects', ['project_id'], ['project_id'])
    op.alter_column('institutions', 'institution_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('institutions', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('institutions', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('institutions', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('institutions', 'country',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'IN'"))
    op.alter_column('institutions', 'website',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('institutions', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('institutions', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_institutions_state'), table_name='institutions')
    op.drop_index(op.f('idx_institutions_type'), table_name='institutions')
    op.alter_column('keywords', 'keyword_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('keywords', 'keyword',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('keywords', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.add_column('labs', sa.Column('research_focus_areas', sa.Text(), nullable=True))
    op.add_column('labs', sa.Column('location_state', sa.String(length=50), nullable=True))
    op.add_column('labs', sa.Column('director_researcher_id', sa.String(length=36), nullable=True))
    op.alter_column('labs', 'lab_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('labs', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('labs', 'institution_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
    op.alter_column('labs', 'research_area',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('labs', 'website',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('labs', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('labs', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.create_index('idx_labs_director', 'labs', ['director_researcher_id'], unique=False)
    op.create_index('idx_labs_location_state', 'labs', ['location_state'], unique=False)
    op.create_foreign_key(None, 'labs', 'researchers', ['director_researcher_id'], ['researcher_id'])
    op.drop_column('labs', 'access_tier')
    op.alter_column('publication_keywords', 'publication_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('publication_keywords', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_publication_keywords_keyword'), table_name='publication_keywords')
    op.drop_index(op.f('idx_publication_keywords_publication'), table_name='publication_keywords')
    op.add_column('publications', sa.Column('authors', sa.Text(), nullable=True))
    op.add_column('publications', sa.Column('researcher_ids', sa.Text(), nullable=True))
    op.add_column('publications', sa.Column('volume', sa.String(length=50), nullable=True))
    op.add_column('publications', sa.Column('issue', sa.String(length=50), nullable=True))
    op.add_column('publications', sa.Column('pages', sa.String(length=50), nullable=True))
    op.add_column('publications', sa.Column('citations', sa.Integer(), nullable=True))
    op.add_column('publications', sa.Column('impact_factor', sa.Float(), nullable=True))
    op.add_column('publications', sa.Column('publication_type', sa.String(length=100), nullable=True))
    op.add_column('publications', sa.Column('research_area', sa.String(length=100), nullable=True))
    op.alter_column('publications', 'publication_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('publications', 'venue',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('publications', 'doi',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('publications', 'pmid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('publications', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('publications', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_publications_doi'), table_name='publications')
    op.drop_index(op.f('idx_publications_venue'), table_name='publications')
    op.drop_index(op.f('idx_publications_year_venue'), table_name='publications')
    op.create_index('idx_publications_citations', 'publications', ['citations'], unique=False)
    op.create_index('idx_publications_research_area', 'publications', ['research_area'], unique=False)
    op.create_index('idx_publications_tier', 'publications', ['access_tier'], unique=False)
    op.alter_column('researcher_labs', 'researcher_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('researcher_labs', 'lab_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('researcher_labs', 'start_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('researcher_labs', 'end_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('researcher_labs', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('researcher_labs', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_researcher_labs_lab'), table_name='researcher_labs')
    op.drop_index(op.f('idx_researcher_labs_researcher'), table_name='researcher_labs')
    op.alter_column('researcher_publications', 'researcher_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('researcher_publications', 'publication_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('researcher_publications', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_researcher_publications_publication'), table_name='researcher_publications')
    op.drop_index(op.f('idx_researcher_publications_researcher'), table_name='researcher_publications')
    op.add_column('researchers', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('researchers', sa.Column('secondary_research_areas', sa.Text(), nullable=True))
    op.add_column('researchers', sa.Column('years_experience', sa.Integer(), nullable=True))
    op.add_column('researchers', sa.Column('h_index', sa.Integer(), nullable=True))
    op.add_column('researchers', sa.Column('total_funding_received_inr_crores', sa.Float(), nullable=True))
    op.alter_column('researchers', 'researcher_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('researchers', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('researchers', 'institution_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
    op.alter_column('researchers', 'state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('researchers', 'research_area',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('researchers', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('researchers', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.alter_column('researchers', 'orcid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('researchers', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('researchers', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('idx_researchers_institution'), table_name='researchers')
    op.drop_index(op.f('idx_researchers_institution_state'), table_name='researchers')
    op.drop_index(op.f('idx_researchers_name'), table_name='researchers')
    op.drop_index(op.f('idx_researchers_research_area_year'), table_name='researchers')
    op.drop_index(op.f('idx_researchers_year'), table_name='researchers')
    op.create_index('idx_researchers_department', 'researchers', ['department'], unique=False)
    op.create_index('idx_researchers_h_index', 'researchers', ['h_index'], unique=False)
    op.create_index('idx_researchers_tier', 'researchers', ['access_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_researchers_tier', table_name='researchers')
    op.drop_index('idx_researchers_h_index', table_name='researchers')
    op.drop_index('idx_researchers_department', table_name='researchers')
    op.create_index(op.f('idx_researchers_year'), 'researchers', ['year_joined'], unique=False)
    op.create_index(op.f('idx_researchers_research_area_year'), 'researchers', ['research_area', 'year_joined'], unique=False)
    op.create_index(op.f('idx_researchers_name'), 'researchers', ['name'], unique=False)
    op.create_index(op.f('idx_researchers_institution_state'), 'researchers', ['institution_id', 'state'], unique=False)
    op.create_index(op.f('idx_researchers_institution'), 'researchers', ['institution_id'], unique=False)
    op.alter_column('researchers', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('researchers', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('researchers', 'orcid',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('researchers', 'phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('researchers', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('researchers', 'research_area',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('researchers', 'state',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('researchers', 'institution_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('researchers', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('researchers', 'researcher_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('researchers', 'total_funding_received_inr_crores')
    op.drop_column('researchers', 'h_index')
    op.drop_column('researchers', 'years_experience')
    op.drop_column('researchers', 'secondary_research_areas')
    op.drop_column('researchers', 'department')
    op.create_index(op.f('idx_researcher_publications_researcher'), 'researcher_publications', ['researcher_id'], unique=False)
    op.create_index(op.f('idx_researcher_publications_publication'), 'researcher_publications', ['publication_id'], unique=False)
    op.alter_column('researcher_publications', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('researcher_publications', 'publication_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('researcher_publications', 'researcher_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('idx_researcher_labs_researcher'), 'researcher_labs', ['researcher_id'], unique=False)
    op.create_index(op.f('idx_researcher_labs_lab'), 'researcher_labs', ['lab_id'], unique=False)
    op.alter_column('researcher_labs', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('researcher_labs', 'role',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('researcher_labs', 'end_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('researcher_labs', 'start_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('researcher_labs', 'lab_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('researcher_labs', 'researcher_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index('idx_publications_tier', table_name='publications')
    op.drop_index('idx_publications_research_area', table_name='publications')
    op.drop_index('idx_publications_citations', table_name='publications')
    op.create_index(op.f('idx_publications_year_venue'), 'publications', ['year', 'venue'], unique=False)
    op.create_index(op.f('idx_publications_venue'), 'publications', ['venue'], unique=False)
    op.create_index(op.f('idx_publications_doi'), 'publications', ['doi'], unique=False)
    op.alter_column('publications', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('publications', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('publications', 'pmid',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('publications', 'doi',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('publications', 'venue',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('publications', 'publication_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('publications', 'research_area')
    op.drop_column('publications', 'publication_type')
    op.drop_column('publications', 'impact_factor')
    op.drop_column('publications', 'citations')
    op.drop_column('publications', 'pages')
    op.drop_column('publications', 'issue')
    op.drop_column('publications', 'volume')
    op.drop_column('publications', 'researcher_ids')
    op.drop_column('publications', 'authors')
    op.create_index(op.f('idx_publication_keywords_publication'), 'publication_keywords', ['publication_id'], unique=False)
    op.create_index(op.f('idx_publication_keywords_keyword'), 'publication_keywords', ['keyword_id'], unique=False)
    op.alter_column('publication_keywords', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('publication_keywords', 'publication_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('labs', sa.Column('access_tier', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
    op.drop_constraint(None, 'labs', type_='foreignkey')
    op.drop_index('idx_labs_location_state', table_name='labs')
    op.drop_index('idx_labs_director', table_name='labs')
    op.alter_column('labs', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('labs', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('labs', 'website',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('labs', 'research_area',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('labs', 'institution_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('labs', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('labs', 'lab_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('labs', 'director_researcher_id')
    op.drop_column('labs', 'location_state')
    op.drop_column('labs', 'research_focus_areas')
    op.alter_column('keywords', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('keywords', 'keyword',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('keywords', 'keyword_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_index(op.f('idx_institutions_type'), 'institutions', ['type'], unique=False)
    op.create_index(op.f('idx_institutions_state'), 'institutions', ['state'], unique=False)
    op.alter_column('institutions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('institutions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('institutions', 'website',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('institutions', 'country',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'IN'"))
    op.alter_column('institutions', 'state',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('institutions', 'type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('institutions', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('institutions', 'institution_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'funding_records', type_='foreignkey')
    op.drop_index('idx_funding_tier', table_name='funding_records')
    op.drop_index('idx_funding_project', table_name='funding_records')
    op.drop_index('idx_funding_fiscal_year', table_name='funding_records')
    op.create_index(op.f('idx_funding_amount'), 'funding_records', ['amount'], unique=False)
    op.alter_column('funding_records', 'updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('funding_records', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('funding_records', 'title',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('funding_records', 'end_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('funding_records', 'start_date',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('funding_records', 'amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('funding_records', 'agency',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('funding_records', 'institution_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('funding_records', 'researcher_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('funding_records', 'funding_id',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('funding_records', 'fiscal_year')
    op.drop_column('funding_records', 'project_id')
    op.create_table('schema_migrations',
    sa.Column('version', sa.TEXT(), nullable=True),
    sa.Column('applied_at', sa.TEXT(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    op.drop_index('idx_projects_tier', table_name='projects')
    op.drop_index('idx_projects_status', table_name='projects')
    op.drop_index('idx_projects_research_area', table_name='projects')
    op.drop_index('idx_projects_pi', table_name='projects')
    op.drop_index('idx_projects_agency', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_research_docs_year', table_name='research_documents')
    op.drop_index('idx_research_docs_tier', table_name='research_documents')
    op.drop_index('idx_research_docs_category', table_name='research_documents')
    op.drop_table('research_documents')
    op.drop_index('idx_patents_tier', table_name='patents')
    op.drop_index('idx_patents_status', table_name='patents')
    op.drop_index('idx_patents_research_area', table_name='patents')
    op.drop_table('patents')
    op.drop_index('idx_collaborations_type', table_name='collaborations')
    op.drop_index('idx_collaborations_tier', table_name='collaborations')
    op.drop_index('idx_collaborations_status', table_name='collaborations')
    op.drop_index('idx_collaborations_partner', table_name='collaborations')
    op.drop_table('collaborations')
    # ### end Alembic commands ###