"""Add db_struct.sql columns missing from production table migration.

Revision ID: schema_parity_columns_001
Revises: add_production_tables_001
Create Date: 2026-04-28

This revision is generated from the db_struct.sql/Alembic column diff.
It keeps later LB-3/LB-6 indexes and RLS policies from referencing columns
that were present in the professor schema but absent from the first table
parity migration.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

revision: str = "schema_parity_columns_001"
down_revision: Union[str, None] = "add_production_tables_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

MISSING_COLUMNS: tuple[tuple[str, str, str], ...] = (
    ('actual_student_strength', 'within_state', 'integer'),
    ('actual_student_strength', 'outside_state', 'integer'),
    ('actual_student_strength', 'outside_country', 'integer'),
    ('actual_student_strength', 'economically_backward', 'integer'),
    ('actual_student_strength', 'reimbursed_by_government', 'integer'),
    ('actual_student_strength', 'reimbursed_by_institution', 'integer'),
    ('actual_student_strength', 'reimbursed_by_private', 'integer'),
    ('actual_student_strength', 'not_reimbursed', 'integer'),
    ('advance_search_data', 'domain', 'text'),
    ('advance_search_data', 'subdomain', 'text'),
    ('advance_search_data', 'institute', 'text'),
    ('advance_search_data', 'url', 'text'),
    ('advance_search_data', 'type', 'text'),
    ('advance_search_data', 'collaboration', 'text'),
    ('advance_search_data', 'metadata', 'text'),
    ('advance_search_data', 'citation_id', 'text'),
    ('advance_search_data', 'total_citations', 'text'),
    ('advance_search_data', 'recent_citations', 'text'),
    ('advance_search_data', 'fcr', 'text'),
    ('advance_search_data', 'rcr', 'text'),
    ('advance_search_data', 'altmetrics_details', 'text'),
    ('advance_search_data', 'altmetrics_counts', 'text'),
    ('advance_search_data', 'document_type', 'text'),
    ('advance_search_data', 'source', 'text'),
    ('advance_search_data', 'open_access_status', 'text'),
    ('advance_search_data', 'sustainable_development_goal', 'text'),
    ('advance_search_data', 'fwci', 'text'),
    ('advance_search_data', 'citation_percentile', 'text'),
    ('advance_search_data', 'cited_by', 'text'),
    ('advance_search_data', 'related_to', 'text'),
    ('advance_search_data', 'orcid', 'text'),
    ('advance_search_data', 'topic', 'text'),
    ('advance_search_data', 'field', 'text'),
    ('advance_search_data', 'subfield', 'text'),
    ('advance_search_data', 'fetched_from', 'text'),
    ('advance_search_data', 'title_backup', 'text'),
    ('advance_search_data', 'abstract_backup', 'text'),
    ('advance_search_data_15_12', 'domain', 'text'),
    ('advance_search_data_15_12', 'subdomain', 'text'),
    ('advance_search_data_15_12', 'institute', 'text'),
    ('advance_search_data_15_12', 'url', 'text'),
    ('advance_search_data_15_12', 'type', 'text'),
    ('advance_search_data_15_12', 'collaboration', 'text'),
    ('advance_search_data_15_12', 'metadata', 'text'),
    ('advance_search_data_15_12', 'citation_id', 'text'),
    ('advance_search_data_15_12', 'total_citations', 'text'),
    ('advance_search_data_15_12', 'recent_citations', 'text'),
    ('advance_search_data_15_12', 'fcr', 'text'),
    ('advance_search_data_15_12', 'rcr', 'text'),
    ('advance_search_data_15_12', 'altmetrics_details', 'text'),
    ('advance_search_data_15_12', 'altmetrics_counts', 'text'),
    ('advance_search_data_15_12', 'document_type', 'text'),
    ('advance_search_data_15_12', 'source', 'text'),
    ('advance_search_data_15_12', 'open_access_status', 'text'),
    ('advance_search_data_15_12', 'sustainable_development_goal', 'text'),
    ('advance_search_data_15_12', 'fwci', 'text'),
    ('advance_search_data_15_12', 'citation_percentile', 'text'),
    ('advance_search_data_15_12', 'cited_by', 'text'),
    ('advance_search_data_15_12', 'related_to', 'text'),
    ('advance_search_data_15_12', 'orcid', 'text'),
    ('advance_search_data_15_12', 'topic', 'text'),
    ('advance_search_data_15_12', 'field', 'text'),
    ('advance_search_data_15_12', 'subfield', 'text'),
    ('advance_search_data_15_12', 'fetched_from', 'text'),
    ('advance_search_data_old', 'domain', 'text'),
    ('advance_search_data_old', 'subdomain', 'text'),
    ('advance_search_data_old', 'institute', 'text'),
    ('advance_search_data_old', 'url', 'text'),
    ('advance_search_data_old', 'type', 'text'),
    ('advance_search_data_old', 'collaboration', 'text'),
    ('advance_search_data_old', 'metadata', 'text'),
    ('advance_search_data_old', 'citation_id', 'text'),
    ('advance_search_data_old', 'total_citations', 'text'),
    ('advance_search_data_old', 'recent_citations', 'text'),
    ('advance_search_data_old', 'fcr', 'text'),
    ('advance_search_data_old', 'rcr', 'text'),
    ('advance_search_data_old', 'altmetrics_details', 'text'),
    ('advance_search_data_old', 'altmetrics_counts', 'text'),
    ('advance_search_data_old', 'document_type', 'text'),
    ('advance_search_data_old', 'source', 'text'),
    ('advance_search_data_old', 'open_access_status', 'text'),
    ('advance_search_data_old', 'sustainable_development_goal', 'text'),
    ('advance_search_data_old', 'fwci', 'text'),
    ('advance_search_data_old', 'citation_percentile', 'text'),
    ('advance_search_data_old', 'cited_by', 'text'),
    ('advance_search_data_old', 'related_to', 'text'),
    ('advance_search_data_old', 'orcid', 'text'),
    ('advance_search_data_old', 'topic', 'text'),
    ('advance_search_data_old', 'field', 'text'),
    ('advance_search_data_old', 'subfield', 'text'),
    ('advance_search_data_old', 'fetched_from', 'text'),
    ('combined_ipo_patent_data', 'source_collection', 'text'),
    ('combined_ipo_patent_data', 'invention_title', 'text'),
    ('combined_ipo_patent_data', 'publication_number', 'text'),
    ('combined_ipo_patent_data', 'publication_type', 'text'),
    ('combined_ipo_patent_data', 'application_filing_date', 'text'),
    ('combined_ipo_patent_data', 'abstract', 'text'),
    ('combined_ipo_patent_data', 'email_record', 'text'),
    ('combined_ipo_patent_data', 'additional_email', 'text'),
    ('combined_ipo_patent_data', 'application_type', 'text'),
    ('combined_ipo_patent_data', 'examination_request_date', 'text'),
    ('combined_ipo_patent_data', 'first_examination_report_date', 'text'),
    ('combined_ipo_patent_data', 'certificate_issue_date', 'text'),
    ('combined_ipo_patent_data', 'post_grant_journal_date', 'text'),
    ('combined_ipo_patent_data', 'reply_to_fer_date', 'text'),
    ('combined_ipo_patent_data', 'patent_number', 'text'),
    ('combined_ipo_patent_data', 'date_of_grant', 'text'),
    ('combined_ipo_patent_data', 'legal_status', 'text'),
    ('combined_ipo_patent_data', 'due_date_next_renewal', 'text'),
    ('combined_ipo_patent_data', 'renewal_history', 'jsonb'),
    ('combined_ipo_patent_data', 'aishe_code', 'text'),
    ('combined_ipo_patent_data', 'fetched_at', 'timestamp without time zone'),
    ('combined_ipo_patent_data', 'granted_patent_title', 'text'),
    ('combined_ipo_patent_data', 'patent_grant_number', 'text'),
    ('combined_ipo_patent_data', 'university_name', 'text'),
    ('combined_ipo_patent_data', 'fetched_from', 'text'),
    ('combined_ipo_patent_data_old', 'source_collection', 'text'),
    ('combined_ipo_patent_data_old', 'invention_title', 'text'),
    ('combined_ipo_patent_data_old', 'publication_number', 'text'),
    ('combined_ipo_patent_data_old', 'publication_type', 'text'),
    ('combined_ipo_patent_data_old', 'application_filing_date', 'text'),
    ('combined_ipo_patent_data_old', 'abstract', 'text'),
    ('combined_ipo_patent_data_old', 'email_record', 'text'),
    ('combined_ipo_patent_data_old', 'additional_email', 'text'),
    ('combined_ipo_patent_data_old', 'application_type', 'text'),
    ('combined_ipo_patent_data_old', 'examination_request_date', 'text'),
    ('combined_ipo_patent_data_old', 'first_examination_report_date', 'text'),
    ('combined_ipo_patent_data_old', 'certificate_issue_date', 'text'),
    ('combined_ipo_patent_data_old', 'post_grant_journal_date', 'text'),
    ('combined_ipo_patent_data_old', 'reply_to_fer_date', 'text'),
    ('combined_ipo_patent_data_old', 'patent_number', 'text'),
    ('combined_ipo_patent_data_old', 'date_of_grant', 'text'),
    ('combined_ipo_patent_data_old', 'legal_status', 'text'),
    ('combined_ipo_patent_data_old', 'due_date_next_renewal', 'text'),
    ('combined_ipo_patent_data_old', 'renewal_history', 'jsonb'),
    ('combined_ipo_patent_data_old', 'aishe_code', 'text'),
    ('combined_ipo_patent_data_old', 'fetched_at', 'timestamp without time zone'),
    ('combined_ipo_patent_data_old', 'granted_patent_title', 'text'),
    ('combined_ipo_patent_data_old', 'patent_grant_number', 'text'),
    ('combined_ipo_patent_data_old', 'university_name', 'text'),
    ('combined_ipo_patent_data_old', 'fetched_from', 'text'),
    ('expertise', 'phd', 'character varying'),
    ('expertise', 'research', 'character varying'),
    ('expertise', 'image', 'character varying'),
    ('expertise', 'department', 'character varying'),
    ('expertise', 'institute', 'character varying'),
    ('faculty_strength', 'male_strength', 'character varying(100)'),
    ('faculty_strength', 'female_strength', 'character varying(100)'),
    ('faculty_strength', 'total_strength', 'character varying(100)'),
    ('faculty_strength', 'total_sanctioned_strength', 'character varying(100)'),
    ('faculty_strength', 'uploaded_on', 'character varying(100)'),
    ('faculty_strength', 'url', 'character varying(100)'),
    ('faculty_strength', 'types', 'character varying(100)'),
    ('fdi_investment', 'as_on_year', 'text'),
    ('fdi_investment', 'id', 'integer'),
    ('fdp_details', 'program_start_date', 'text'),
    ('fdp_details', 'program_end_date', 'text'),
    ('fdp_details', 'institute', 'text'),
    ('fdp_details', 'as_on_year', 'text'),
    ('fdp_details', 'id', 'integer'),
    ('financial_expenses_capital', 'capital_assets', 'bigint'),
    ('financial_expenses_capital', 'as_on_year', 'text'),
    ('financial_expenses_operational', 'as_on_year', 'text'),
    ('founders_of_fortune_500_companies', 'year_of_appearence', 'text'),
    ('founders_of_fortune_500_companies', 'institute', 'text'),
    ('founders_of_fortune_500_companies', 'as_on_year', 'text'),
    ('founders_of_fortune_500_companies', 'id', 'integer'),
    ('innovation_grant_from_govt', 'as_on_year', 'text'),
    ('ipo_patent_details_flat', 'source_collection', 'text'),
    ('ipo_patent_details_flat', 'invention_title', 'text'),
    ('ipo_patent_details_flat', 'publication_number', 'text'),
    ('ipo_patent_details_flat', 'publication_type', 'text'),
    ('ipo_patent_details_flat', 'application_filing_date', 'text'),
    ('ipo_patent_details_flat', 'abstract', 'text'),
    ('ipo_patent_details_flat', 'email_record', 'text'),
    ('ipo_patent_details_flat', 'additional_email', 'text'),
    ('ipo_patent_details_flat', 'application_type', 'text'),
    ('ipo_patent_details_flat', 'examination_request_date', 'text'),
    ('ipo_patent_details_flat', 'first_examination_report_date', 'text'),
    ('ipo_patent_details_flat', 'certificate_issue_date', 'text'),
    ('ipo_patent_details_flat', 'post_grant_journal_date', 'text'),
    ('ipo_patent_details_flat', 'reply_to_fer_date', 'text'),
    ('ipo_patent_details_flat', 'patent_number', 'text'),
    ('ipo_patent_details_flat', 'date_of_grant', 'text'),
    ('ipo_patent_details_flat', 'legal_status', 'text'),
    ('ipo_patent_details_flat', 'due_date_next_renewal', 'text'),
    ('ipo_patent_details_flat', 'renewal_history', 'jsonb'),
    ('ipo_patent_details_flat_old', 'source_collection', 'text'),
    ('ipo_patent_details_flat_old', 'invention_title', 'text'),
    ('ipo_patent_details_flat_old', 'publication_number', 'text'),
    ('ipo_patent_details_flat_old', 'publication_type', 'text'),
    ('ipo_patent_details_flat_old', 'application_filing_date', 'text'),
    ('ipo_patent_details_flat_old', 'abstract', 'text'),
    ('ipo_patent_details_flat_old', 'email_record', 'text'),
    ('ipo_patent_details_flat_old', 'additional_email', 'text'),
    ('ipo_patent_details_flat_old', 'application_type', 'text'),
    ('ipo_patent_details_flat_old', 'examination_request_date', 'text'),
    ('ipo_patent_details_flat_old', 'first_examination_report_date', 'text'),
    ('ipo_patent_details_flat_old', 'certificate_issue_date', 'text'),
    ('ipo_patent_details_flat_old', 'post_grant_journal_date', 'text'),
    ('ipo_patent_details_flat_old', 'reply_to_fer_date', 'text'),
    ('ipo_patent_details_flat_old', 'patent_number', 'text'),
    ('ipo_patent_details_flat_old', 'date_of_grant', 'text'),
    ('ipo_patent_details_flat_old', 'legal_status', 'text'),
    ('ipo_patent_details_flat_old', 'due_date_next_renewal', 'text'),
    ('ipo_patent_details_flat_old', 'renewal_history', 'jsonb'),
    ('nirf_extracted_table', 'created_at', 'timestamp with time zone'),
    ('nirf_pdf_record', 'pdf_name', 'character varying(255)'),
    ('phd_students', 'graduate', 'integer'),
    ('placements_and_higher_studies', 'students_admitted', 'integer'),
    ('placements_and_higher_studies', 'year_of_lateral_entry', 'text'),
    ('placements_and_higher_studies', 'students_admitted_lateral_entry', 'integer'),
    ('placements_and_higher_studies', 'year_of_graduation', 'text'),
    ('placements_and_higher_studies', 'graduated_students', 'integer'),
    ('placements_and_higher_studies', 'placed_students', 'integer'),
    ('placements_and_higher_studies', 'median_salary_per_annum', 'bigint'),
    ('placements_and_higher_studies', 'higher_studies_students', 'integer'),
    ('research_consultancy_details_consultancy', 'amount_recieved_consultancy_projects', 'bigint'),
    ('research_consultancy_details_sponsered', 'amount_recieved_sponsered_research', 'bigint'),
    ('scraped_data', 'domain', 'text'),
    ('scraped_data', 'subdomain', 'text'),
    ('scraped_data', 'institute', 'text'),
    ('scraped_data', 'url', 'text'),
    ('scraped_data', 'type', 'text'),
    ('scraped_data', 'collaboration', 'text'),
    ('scraped_data', 'metadata', 'text'),
    ('scraped_data', 'citation_id', 'text'),
    ('scraped_data', 'total_citations', 'text'),
    ('scraped_data', 'recent_citations', 'text'),
    ('scraped_data', 'fcr', 'text'),
    ('scraped_data', 'rcr', 'text'),
    ('scraped_data', 'altmetrics_details', 'text'),
    ('scraped_data', 'altmetrics_counts', 'text'),
    ('scraped_data', 'document_type', 'text'),
    ('scraped_data', 'source', 'text'),
    ('scraped_data', 'open_access_status', 'text'),
    ('scraped_data', 'sustainable_development_goal', 'text'),
    ('scraped_data', 'fwci', 'text'),
    ('scraped_data', 'citation_percentile', 'text'),
    ('scraped_data', 'cited_by', 'text'),
    ('scraped_data', 'related_to', 'text'),
    ('scraped_data', 'orcid', 'text'),
    ('scraped_data', 'topic', 'text'),
    ('scraped_data', 'field', 'text'),
    ('scraped_data', 'subfield', 'text'),
    ('scraped_data', 'fetched_from', 'text'),
    ('scraped_data', 'upload_date', 'date'),
    ('scraped_data_save', 'domain', 'text'),
    ('scraped_data_save', 'subdomain', 'text'),
    ('scraped_data_save', 'institute', 'text'),
    ('scraped_data_save', 'url', 'text'),
    ('scraped_data_save', 'type', 'text'),
    ('scraped_data_save', 'collaboration', 'text'),
    ('scraped_data_save', 'metadata', 'text'),
    ('scraped_data_save', 'citation_id', 'text'),
    ('scraped_data_save', 'total_citations', 'text'),
    ('scraped_data_save', 'recent_citations', 'text'),
    ('scraped_data_save', 'fcr', 'text'),
    ('scraped_data_save', 'rcr', 'text'),
    ('scraped_data_save', 'altmetrics_details', 'text'),
    ('scraped_data_save', 'altmetrics_counts', 'text'),
    ('scraped_data_save', 'document_type', 'text'),
    ('scraped_data_save', 'source', 'text'),
    ('scraped_data_save', 'open_access_status', 'text'),
    ('scraped_data_save', 'sustainable_development_goal', 'text'),
    ('scraped_data_save', 'fwci', 'text'),
    ('scraped_data_save', 'citation_percentile', 'text'),
    ('scraped_data_save', 'cited_by', 'text'),
    ('scraped_data_save', 'related_to', 'text'),
    ('scraped_data_save', 'orcid', 'text'),
    ('scraped_data_save', 'topic', 'text'),
    ('scraped_data_save', 'field', 'text'),
    ('scraped_data_save', 'subfield', 'text'),
    ('scraped_data_save', 'fetched_from', 'text'),
    ('scraped_data_save', 'upload_date', 'date'),
    ('scraped_raw_data', 'domain', 'text'),
    ('scraped_raw_data', 'subdomain', 'text'),
    ('scraped_raw_data', 'institute', 'text'),
    ('scraped_raw_data', 'url', 'text'),
    ('scraped_raw_data', 'type', 'text'),
    ('scraped_raw_data', 'collaboration', 'text'),
    ('scraped_raw_data', 'metadata', 'text'),
    ('scraped_raw_data', 'citation_id', 'text'),
    ('scraped_raw_data', 'total_citations', 'text'),
    ('scraped_raw_data', 'recent_citations', 'text'),
    ('scraped_raw_data', 'fcr', 'text'),
    ('scraped_raw_data', 'rcr', 'text'),
    ('scraped_raw_data', 'altmetrics_details', 'text'),
    ('scraped_raw_data', 'altmetrics_counts', 'text'),
    ('scraped_raw_data', 'document_type', 'text'),
    ('scraped_raw_data', 'source', 'text'),
    ('scraped_raw_data', 'open_access_status', 'text'),
    ('scraped_raw_data', 'sustainable_development_goal', 'text'),
    ('scraped_raw_data', 'fwci', 'text'),
    ('scraped_raw_data', 'citation_percentile', 'text'),
    ('scraped_raw_data', 'cited_by', 'text'),
    ('scraped_raw_data', 'related_to', 'text'),
    ('scraped_raw_data', 'orcid', 'text'),
    ('scraped_raw_data', 'topic', 'text'),
    ('scraped_raw_data', 'field', 'text'),
    ('scraped_raw_data', 'subfield', 'text'),
    ('scraped_raw_data', 'fetched_from', 'text'),
    ('scraped_raw_data', 'upload_date', 'date'),
    ('seed_funding', 'govt_org', 'character varying(255)'),
    ('seed_funding', 'year_of_receiving_fund', 'character varying(10)'),
    ('seed_funding', 'achievement_level', 'character varying(255)'),
    ('seed_funding', 'type_of_investment', 'character varying(255)'),
    ('startup_receiving_vc_investment', 'id', 'integer'),
    ('startup_recognition', 'id', 'integer'),
    ('startup_recognition_old', 'id', 'integer'),
    ('tb_goi_ministries_mstr', 'phone_no', 'character varying'),
    ('tb_goi_ministries_mstr', 'website', 'character varying'),
    ('tb_institute_mstr', 'established_year', 'integer'),
    ('tb_institute_mstr', 'website_url', 'character varying'),
    ('tb_institute_scrap_data_url', 'city', 'character varying(100)'),
    ('tb_institute_scrap_data_url', 'state', 'character varying(100)'),
    ('tb_institute_scrap_data_url', 'established_year', 'integer'),
    ('tb_institute_scrap_data_url', 'address', 'text'),
    ('tb_institute_scrap_data_url', 'website_url', 'text'),
    ('tb_institute_scrap_data_url', 'scrap_data_url', 'text'),
    ('user_registration', 'confirm_password', 'character varying(128)'),
    ('user_registration', 'phone_number', 'character varying(15)'),
    ('user_registration', 'is_approved', 'boolean'),
    ('user_registration', 'user_info', 'character varying'),
    ('user_registration', 'status', 'character varying'),
    ('user_registration', 'deleted_by', 'character varying'),
    ('user_registration', 'is_email_verified', 'boolean'),
    ('user_registration', 'email_otp', 'character varying'),
    ('user_registration', 'is_otp_verified', 'boolean'),
    ('user_registration', 'first_password', 'character varying'),
    ('user_registration', 'first_login', 'boolean'),
    ('user_registration', 'email_status', 'character varying'),
)

def _column_type(db_type: str) -> sa.types.TypeEngine:
    normalized = db_type.lower()
    if normalized == "integer":
        return sa.Integer()
    if normalized == "bigint":
        return sa.BigInteger()
    if normalized == "smallint":
        return sa.SmallInteger()
    if normalized == "boolean":
        return sa.Boolean()
    if normalized == "date":
        return sa.Date()
    if normalized == "timestamp with time zone":
        return sa.DateTime(timezone=True)
    if normalized == "timestamp without time zone":
        return sa.DateTime()
    if normalized == "jsonb":
        return sa.JSON()
    varchar_match = normalized.startswith("character varying")
    if varchar_match:
        match = __import__("re").search(r"\((\d+)\)", normalized)
        return sa.String(length=int(match.group(1))) if match else sa.String()
    return sa.Text()

def _existing_columns() -> dict[str, set[str]]:
    inspector = inspect(op.get_bind())
    table_names = set(inspector.get_table_names())
    return {table: {column["name"] for column in inspector.get_columns(table)} for table in table_names}

def upgrade() -> None:
    existing = _existing_columns()
    dialect_name = op.get_context().dialect.name
    for table_name, column_name, db_type in MISSING_COLUMNS:
        if table_name not in existing or column_name in existing[table_name]:
            continue
        op.add_column(
            table_name,
            sa.Column(column_name, _column_type(db_type), nullable=True),
            if_not_exists=dialect_name != "sqlite",
        )
        existing[table_name].add(column_name)

def downgrade() -> None:
    existing = _existing_columns()
    for table_name, column_name, _db_type in reversed(MISSING_COLUMNS):
        if table_name in existing and column_name in existing[table_name]:
            op.drop_column(table_name, column_name)
            existing[table_name].remove(column_name)
