apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nrg-servicemonitor
  labels:
    app: nrg-api
spec:
  selector:
    matchLabels:
      app: nrg-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}