"""C4 Load Test — 1000 concurrent users, P99 < 500ms SLO.

Usage:
    # Local development:
    locust -f tests/load/locustfile_c4.py \
        --headless \
        --users 1000 \
        --spawn-rate 50 \
        --run-time 5m \
        --host http://localhost:8000 \
        --html /tmp/c4_report.html

    # Sovereign cluster (Kubernetes):
    kubectl exec -it nrg-api-deploy-xxx -- locust -f /app/locustfile_c4.py \
        --headless \
        --users 1000 \
        --spawn-rate 100 \
        --run-time 5m \
        --host http://localhost:8000 \
        --html /tmp/c4_report_$(date +%Y%m%d_%H%M%S).html

SLO: P99 < 500ms @ 1000 concurrent users
"""

from locust import HttpUser, task, between, events
import os
import random
import statistics

_response_times: list = []


def _credentials(
    username_env: str,
    default_username: str,
    password_env: str,
    default_password: str,
) -> dict[str, str]:
    return {
        "username": os.environ.get(username_env, default_username),
        "password": os.environ.get(password_env, default_password),
    }


def _has_query_payload(data: dict) -> bool:
    return bool(
        data.get("sql_query")
        or data.get("sql_results")
        or data.get("response")
        or data.get("answer")
        or data.get("sql")
        or data.get("results")
    )


def _handle_query_response(resp) -> None:
    if resp.status_code == 200:
        try:
            data = resp.json()
        except Exception:
            resp.failure("JSON parse error")
            return
        if _has_query_payload(data):
            resp.success()
        else:
            resp.failure("Empty response")
    elif resp.status_code == 429:
        resp.success()
    else:
        resp.failure(f"HTTP {resp.status_code}")


def _handle_login_failure(user: HttpUser, response) -> None:
    user.headers = {}
    response.failure(f"Login failed: {response.status_code}")
    if user.environment.runner:
        user.environment.runner.quit()


@events.request.add_listener
def on_request(request_type, name, response_time, response_length, exception, **kwargs):
    if exception is None and 0 < response_time < 30000:
        _response_times.append(response_time)


@events.test_stop.add_listener
def on_test_stop(environment, **kwargs):
    if _response_times:
        sorted_times = sorted(_response_times)
        p50 = sorted_times[int(len(sorted_times) * 0.50)]
        p90 = sorted_times[int(len(sorted_times) * 0.90)]
        p95 = sorted_times[int(len(sorted_times) * 0.95)]
        p99 = sorted_times[int(len(sorted_times) * 0.99)]
        p999 = sorted_times[int(len(sorted_times) * 0.999)]

        print("\n" + "=" * 60)
        print("C4 LOAD TEST — RESPONSE TIME DISTRIBUTION")
        print("=" * 60)
        print(f"  Total samples : {len(sorted_times):>10,}")
        print(f"  Mean          : {statistics.mean(_response_times):>10.1f} ms")
        print(f"  Median (P50)  : {p50:>10.1f} ms")
        print(f"  P90           : {p90:>10.1f} ms")
        print(f"  P95           : {p95:>10.1f} ms")
        print(f"  P99           : {p99:>10.1f} ms  ← C4 SLO target < 500 ms")
        print(f"  P99.9         : {p999:>10.1f} ms")
        print(f"  Max           : {max(_response_times):>10.1f} ms")
        print("=" * 60)

        if p99 < 500:
            print("✅ C4 PASS — P99 {:.1f}ms < 500ms SLO".format(p99))
        else:
            print("❌ C4 FAIL — P99 {:.1f}ms > 500ms SLO".format(p99))
        print("=" * 60)


RESEARCHER_QUERIES = [
    "find robotics researchers in Gujarat",
    "AI researchers in Karnataka",
    "publications on machine learning",
    "labs working on renewable energy",
    "funding for IIT Bombay projects",
    "what patents does Dr. Sharma have",
    "show me all publications from IISc in 2024",
    "researchers with h_index > 50 in computer science",
    "collaborations between IITGN and foreign universities",
    "PhD students in machine learning",
    "lab directors by research area",
    "funding agencies for electronics research",
]

GOVERNMENT_QUERIES = [
    "total researchers by state",
    "funding trends by year",
    "publication counts by institution",
    "state-wise research area distribution",
    "total funding by agency",
    "institution type breakdown",
    "research output by year",
    "collaboration statistics by country",
    "top funded research areas",
]

INDUSTRY_QUERIES = [
    "labs with industry partnerships",
    "patent opportunities in AI",
    "technology transfer candidates",
    "researchers open to collaboration",
    "consultancy projects in data science",
    "startup incubation results",
    "IP generated by institution",
    "industry-funded research projects",
]


class C4ResearcherUser(HttpUser):
    """Researcher persona — 1000 weight units, bursty query pattern."""
    wait_time = between(1, 3)
    weight = 50

    def on_start(self):
        r = self.client.post(
            "/auth/login",
            json=_credentials(
                "LOAD_TEST_RESEARCHER_USER",
                "researcher_user",
                "LOAD_TEST_RESEARCHER_PASS",
                "researcher-pass",
            ),
            catch_response=True,
        )
        if r.status_code == 200:
            self.token = r.json().get("access_token")
            self.headers = {"Authorization": f"Bearer {self.token}"}
            r.success()
        else:
            _handle_login_failure(self, r)

    @task(8)
    def query(self):
        query_text = random.choice(RESEARCHER_QUERIES)
        with self.client.post("/query",
            headers=self.headers,
            json={"query": query_text, "session_id": "c4-load-test"},
            catch_response=True,
            name="/query"
        ) as resp:
            _handle_query_response(resp)


class C4GovernmentUser(HttpUser):
    """Government persona — 300 weight units, aggregate queries."""
    wait_time = between(2, 5)
    weight = 30

    def on_start(self):
        r = self.client.post(
            "/auth/login",
            json=_credentials(
                "LOAD_TEST_GOV_USER",
                "gov_user",
                "LOAD_TEST_GOV_PASS",
                "government-pass",
            ),
            catch_response=True,
        )
        if r.status_code == 200:
            self.token = r.json().get("access_token")
            self.headers = {"Authorization": f"Bearer {self.token}"}
            r.success()
        else:
            _handle_login_failure(self, r)

    @task(5)
    def aggregate(self):
        query_text = random.choice(GOVERNMENT_QUERIES)
        with self.client.post("/query",
            headers=self.headers,
            json={"query": query_text, "session_id": "c4-load-test"},
            catch_response=True,
            name="/query"
        ) as resp:
            _handle_query_response(resp)


class C4IndustryUser(HttpUser):
    """Industry persona — 150 weight units, partnership searches."""
    wait_time = between(3, 8)
    weight = 15

    def on_start(self):
        r = self.client.post(
            "/auth/login",
            json=_credentials(
                "LOAD_TEST_INDUSTRY_USER",
                "industry_user",
                "LOAD_TEST_INDUSTRY_PASS",
                "industry-pass",
            ),
            catch_response=True,
        )
        if r.status_code == 200:
            self.token = r.json().get("access_token")
            self.headers = {"Authorization": f"Bearer {self.token}"}
            r.success()
        else:
            _handle_login_failure(self, r)

    @task(4)
    def partnership(self):
        query_text = random.choice(INDUSTRY_QUERIES)
        with self.client.post("/query",
            headers=self.headers,
            json={"query": query_text, "session_id": "c4-load-test"},
            catch_response=True,
            name="/query"
        ) as resp:
            _handle_query_response(resp)

    @task(1)
    def stats(self):
        with self.client.get("/stats", headers=self.headers,
            catch_response=True, name="/stats") as resp:
            if resp.status_code == 200:
                resp.success()
            else:
                resp.failure(f"HTTP {resp.status_code}")
