#!/usr/bin/env python3
"""Benchmark harness - generates performance report."""

import argparse
import json
import time
import statistics
from pathlib import Path
from datetime import datetime
import yaml


def load_golden_queries(path: str):
    """Load golden queries from YAML."""
    with open(path) as f:
        return yaml.safe_load(f)


def run_benchmark(queries: list, base_url: str = "http://localhost:8000"):
    """Run benchmark suite."""
    import httpx
    
    results = {
        "timestamp": datetime.utcnow().isoformat(),
        "total_queries": len(queries),
        "queries": [],
        "latencies": [],
        "errors": 0,
        "factual_consistency": 0,
        "rbac_denial": 0,
    }
    
    client = httpx.Client(timeout=30.0)
    
    for q in queries:
        query_text = q["query"]
        tier = q.get("tier", 1)
        
        start = time.monotonic()
        try:
            response = client.post(
                f"{base_url}/query",
                json={"query": query_text, "tier": tier},
            )
            latency = (time.monotonic() - start) * 1000
            
            if response.status_code == 200:
                data = response.json()
                results["queries"].append({
                    "query": query_text,
                    "latency_ms": latency,
                    "status": "success",
                    "row_count": data.get("row_count", 0),
                })
                results["latencies"].append(latency)
                
                if "citations" in q:
                    has_citations = bool(data.get("citations", []))
                    if has_citations:
                        results["factual_consistency"] += 1
                        results["factual_consistency"] = (results["factual_consistency"] / len(queries)) * 100
            elif response.status_code == 403:
                results["rbac_denial"] += 1
                results["errors"] += 1
            else:
                results["errors"] += 1
                
        except Exception as e:
            results["errors"] += 1
            results["queries"].append({
                "query": query_text,
                "latency_ms": 0,
                "status": "error",
                "error": str(e),
            })
    
    client.close()
    
    if results["latencies"]:
        results["p50"] = statistics.median(results["latencies"])
        results["p95"] = statistics.quantiles(results["latencies"], 19)[18] if len(results["latencies"]) >= 20 else max(results["latencies"])
        results["p99"] = max(results["latencies"]) if len(results["latencies"]) < 100 else statistics.quantiles(results["latencies"], 99)[98]
    
    return results


def generate_report(results: dict, output_path: str):
    """Generate markdown report."""
    report = f"""# NRG Performance Report

**Timestamp**: {results['timestamp']}

## Summary

| Metric | Value |
|--------|-------|
| Total Queries | {results['total_queries']} |
| Errors | {results['errors']} |
| RBAC Denials | {results['rbac_denial']} |
| Factual Consistency | {results['factual_consistency']:.1f}% |

## Latency

| Percentile | Latency (ms) |
|-----------|-------------|
| P50 | {results.get('p50', 0):.1f} |
| P95 | {results.get('p95', 0):.1f} |
| P99 | {results.get('p99', 0):.1f} |

## SLA Gates

| Threshold | Status |
|----------|--------|
| p95 < 2000ms | {'✅' if results.get('p95', 0) < 2000 else '❌'} |
| factual_consistency > 95% | {'✅' if results['factual_consistency'] > 95 else '❌'} |

---
*Generated by NRG Benchmark Harness*
"""
    
    with open(output_path, "w") as f:
        f.write(report)
    
    return report


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--queries", default="tests/perf/golden_queries.yaml")
    parser.add_argument("--url", default="http://localhost:8000")
    parser.add_argument("--output", default="docs/benchmarks/REPORT.md")
    args = parser.parse_args()
    
    queries = load_golden_queries(args.queries)
    results = run_benchmark(queries, args.url)
    report = generate_report(results, args.output)
    
    print(report)
    print(f"\nReport saved to {args.output}")


if __name__ == "__main__":
    main()