#!/usr/bin/env bash
# Final critical-path orchestrator.
#
# This script intentionally delegates stack boot, strict health validation,
# migrations, persona login verification, prewarm, Playwright screenshots, and
# video capture to scripts/run_critical_path.sh. That keeps the laptop path to
# one maintained boot flow. The final-only work here is MiniMax preflight and
# the 5 golden questions x 3 tiers answer-quality capture.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EVIDENCE_DATE="${NRG_EVIDENCE_DATE:-2026-04-28}"
EVIDENCE_DIR="${ROOT_DIR}/evidence/${EVIDENCE_DATE}/critical_path"
API_BASE="${API_BASE:-http://localhost:8000}"
FRONTEND_BASE="${FRONTEND_BASE:-http://localhost:5173}"
RESET=0
WALK=1
SKIP_BOOT=0

usage() {
  cat <<'EOF'
Usage: bash scripts/run_critical_path_final.sh [--reset] [--no-walk] [--skip-boot]

Options:
  --reset      Reset Docker volumes through the verified critical-path runner.
  --no-walk    Skip Playwright walk capture in the delegated runner.
  --skip-boot  Do not boot the stack; only capture golden answers against API_BASE.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --reset) RESET=1 ;;
    --no-walk) WALK=0 ;;
    --skip-boot) SKIP_BOOT=1 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
  esac
  shift
done

cd "${ROOT_DIR}"
mkdir -p "${EVIDENCE_DIR}"

log() { printf '\n[%s] %s\n' "$(date +%H:%M:%S)" "$*"; }
ok() { printf 'OK: %s\n' "$*"; }
warn() { printf 'WARN: %s\n' "$*" >&2; }
fail() { printf 'FAIL: %s\n' "$*" >&2; exit 1; }

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required"
}

env_value() {
  local key="$1"
  awk -F= -v key="${key}" '$1 == key {print substr($0, index($0, "=") + 1); exit}' .env
}

http_post_json() {
  local url="$1"
  local payload="$2"
  local output="$3"
  shift 3
  local http_code
  http_code=$(curl -sS -o "${output}" -w '%{http_code}' \
    -X POST "${url}" \
    -H 'Content-Type: application/json' \
    "$@" \
    -d "${payload}" || true)
  if [[ "${http_code}" -lt 200 || "${http_code}" -ge 300 ]]; then
    cat "${output}" >&2 || true
    fail "POST ${url} returned HTTP ${http_code}; see ${output}"
  fi
}

json_get() {
  local file="$1"
  local expr="$2"
  jq -r "${expr}" "${file}"
}

log "0/4 final preflight"
require_cmd bash
require_cmd curl
require_cmd jq
[[ -f .env ]] || fail ".env is missing"
[[ -f scripts/run_critical_path.sh ]] || fail "scripts/run_critical_path.sh is missing"
bash -n scripts/run_critical_path.sh

if [[ -z "$(env_value MINIMAX_API_KEY)" ]]; then
  fail "MINIMAX_API_KEY missing in .env"
fi
if [[ "$(env_value LLM_PROVIDER)" != "minimax" ]]; then
  warn "LLM_PROVIDER is not minimax"
fi
ok "MiniMax env and verified runner are present"

if [[ "${SKIP_BOOT}" -eq 0 ]]; then
  log "1/4 strict critical-path boot and walk"
  runner_args=(--strict)
  [[ "${RESET}" -eq 1 ]] && runner_args+=(--reset)
  if [[ "${WALK}" -eq 1 ]]; then
    runner_args+=(--walk)
  fi
  NRG_EVIDENCE_DATE="${EVIDENCE_DATE}" bash scripts/run_critical_path.sh "${runner_args[@]}"
else
  log "1/4 using already-running stack"
fi

log "2/4 login tokens for golden answers"
credentials=(
  't1:researcher@iitgn.ac.in:Researcher@2026'
  't2:ministry@nrg.gov.in:Ministry@2026'
  't3:partner@industry.in:Industry@2026'
)

for item in "${credentials[@]}"; do
  IFS=: read -r tier username password <<< "${item}"
  login_file="${EVIDENCE_DIR}/cp_login_curl_${tier}.txt"
  http_post_json \
    "${API_BASE}/auth/login" \
    "{\"username\":\"${username}\",\"password\":\"${password}\"}" \
    "${login_file}"
  json_get "${login_file}" '.access_token' >/dev/null
  ok "${tier} token captured"
done

log "3/4 golden answers: 5 questions x 3 tiers"
golden_file="${EVIDENCE_DIR}/cp0_golden_answers.md"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "${tmp_dir}"' EXIT

questions=(
  "Top 5 funding agencies by total grant amount last 5 years"
  "Compare Gujarat and Karnataka AI research output 5y; show gap"
  "Which IITs collaborate most on hydrogen catalysis?"
  "How many TRL-9 innovations exist in clean energy by state?"
  "Show me institutes that doubled grant size between FY22 and FY24"
)

{
  printf '# Golden Answers - %s\n\n' "${EVIDENCE_DATE}"
  printf 'Generated by `scripts/run_critical_path_final.sh` against `%s`.\n' "${API_BASE}"
} > "${golden_file}"

for tier in t1 t2 t3; do
  token="$(json_get "${EVIDENCE_DIR}/cp_login_curl_${tier}.txt" '.access_token')"
  for idx in "${!questions[@]}"; do
    q="${questions[${idx}]}"
    response_file="${tmp_dir}/${tier}_g$((idx + 1)).json"
    started_at="$(date +%s)"
    http_post_json \
      "${API_BASE}/query" \
      "{\"question\":$(jq -Rn --arg q "${q}" '$q')}" \
      "${response_file}" \
      -H "Authorization: Bearer ${token}" \
      --max-time 45
    duration="$(( $(date +%s) - started_at ))"

    {
      printf '\n## %s - G%s - %ss\n\n' "${tier}" "$((idx + 1))" "${duration}"
      printf '**Q:** %s\n\n' "${q}"
      printf '**Answer:**\n\n'
      jq -r '.final_answer // .answer // .response // .text // .synthesized_response // (.|@json)' "${response_file}" | head -80
      printf '\n\n**SQL:**\n\n```sql\n'
      jq -r '.sql_query // .sql // .metadata.sql_query // ""' "${response_file}"
      printf '\n```\n'
      printf '\n**Raw response:** `%s`\n' "$(basename "${response_file}")"
    } >> "${golden_file}"
  done
  ok "${tier} golden answers captured"
done

log "4/4 final summary"
summary="${EVIDENCE_DIR}/SUMMARY_FINAL.md"
{
  printf '# Critical Path Final Run - %s\n\n' "${EVIDENCE_DATE}"
  printf -- '- Commit: %s\n' "$(git rev-parse HEAD 2>/dev/null || echo unknown)"
  printf -- '- API: %s\n' "${API_BASE}"
  printf -- '- Frontend: %s\n' "${FRONTEND_BASE}"
  printf -- '- Strict runner: %s\n' "$([[ "${SKIP_BOOT}" -eq 0 ]] && echo ran || echo skipped)"
  printf -- '- Playwright walk: %s\n' "$([[ "${WALK}" -eq 1 && "${SKIP_BOOT}" -eq 0 ]] && echo ran || echo skipped)"
  printf -- '- Golden answers: %s\n\n' "${golden_file}"
  printf 'Next manual gate: eyeball the 15 golden-answer cells and accept at least 13/15 before the founder dry-run.\n'
} > "${summary}"

ok "final summary written to ${summary}"
printf '\nREADY - %s\n' "${FRONTEND_BASE}"
printf 'T1 researcher@iitgn.ac.in / Researcher@2026\n'
printf 'T2 ministry@nrg.gov.in / Ministry@2026\n'
printf 'T3 partner@industry.in / Industry@2026\n'
